CREATE SCHEMA IF NOT EXISTS monaco;

CREATE TABLE IF NOT EXISTS monaco.file (
	id INT NOT NULL AUTO_INCREMENT,
    password_hash VARCHAR(100) NOT NULL,
    filename VARCHAR(100) NOT NULL,
	filetype ENUM('java', 'ts', 'c', 'cpp', 'py', 'html', 'css', 'js') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( id )
);